version: "3.4"

networks:
  pizzanetwork:
    name: pizzanetwork

services:
  web:
    image: biaaly13/pizzaportalweb
    restart: on-failure
    ports:
      - 8080:80
      - 8081:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORTS=8081
    networks:
      - pizzanetwork
    volumes:
      - ${APPDATA}\Microsoft\UserSecrets\38d54f53-1030-4437-be3f-20270cee7ac4\:/root/.microsoft/usersecrets/38d54f53-1030-4437-be3f-20270cee7ac4
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/
    depends_on:
      - mssql_local

  mssql_local:
    image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
    container_name: "mssql_local"
    restart: on-failure
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Qwerty!1
      - MSSQL_PID=Express
    ports:
      - 1431:1433
    networks:
      - pizzanetwork
