// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PizzaPortal.Migrations;

namespace PizzaPortal.Migrations.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200422121540_Add_IsPreferredPizza_Field_Pizza_Table")]
    partial class Add_IsPreferredPizza_Field_Pizza_Table
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PizzaPortal.Model.Models.CategoryDTO", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("PizzaPortal.Model.Models.PizzaDTO", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CategoryId");

                    b.Property<string>("Description");

                    b.Property<bool>("IsPreferredPizza");

                    b.Property<string>("Name");

                    b.Property<decimal>("Price");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Pizzas");
                });

            modelBuilder.Entity("PizzaPortal.Model.Models.ShoppingCartItemDTO", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Amount");

                    b.Property<string>("PizzaId");

                    b.Property<string>("ShoppingCartId");

                    b.HasKey("Id");

                    b.HasIndex("PizzaId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("PizzaPortal.Model.Models.PizzaDTO", b =>
                {
                    b.HasOne("PizzaPortal.Model.Models.CategoryDTO", "Category")
                        .WithMany("Pizzas")
                        .HasForeignKey("CategoryId");
                });

            modelBuilder.Entity("PizzaPortal.Model.Models.ShoppingCartItemDTO", b =>
                {
                    b.HasOne("PizzaPortal.Model.Models.PizzaDTO", "Pizza")
                        .WithMany()
                        .HasForeignKey("PizzaId");
                });
#pragma warning restore 612, 618
        }
    }
}
